### ISSUE TITLE
It's not showing file names in output.

### ISSUE THREAD

**Issue by jitendravyas** [Dreamseer/stylelint-formatter-pretty#3]

**Comment by Dreamseer** [comment]
Actually the [test for this](https://github.com/Dreamseer/stylelint-formatter-pretty/blob/master/test/test.js#L8-L12) and a manual run prove sth. different. Can you provide some more information and/or some code? Do you use the Stylelint CLI? Grunt? Gulp? Webpack?

**Comment by jitendravyas** [comment]
Sorry, it is there. because this formatter add empty line between each message so when you have long error list the file name is on top takes time to reach to it. 

I thought it was not there after some scrolling but I found it later by scrolling a lot :-)
