### ISSUE TITLE
ESM version (3.x) not working with Stylelint CLI

### ISSUE THREAD

**Issue by ElyDotDev** [Dreamseer/stylelint-formatter-pretty#41]
**Describe the bug**
As the `3.x` version moved to ESM, usage with Stylelint CLI is not working anymore.

**To Reproduce**
1. Add `--custom-formatter=node_modules/stylelint-formatter-pretty ` to stylelint script that uses CLI directly.
2. Run the stylelint script.
4. See the error like below:
```bash
$ stylelint --cache --custom-formatter=node_modules/stylelint-formatter-pretty src/**/*.{css,scss}
Error [ERR_REQUIRE_ESM]: require() of ES Module XXX\node_modules\stylelint-formatter-pretty\index.js from XXX\node_modules\stylelint\lib\cli.js not supported.
Instead change the require of index.js in XXX\node_modules\stylelint\lib\cli.js to a dynamic import() which is available in all CommonJS modules.
    at require (XXX\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at module.exports (XXX\node_modules\stylelint\lib\cli.js:344:15)
    at Object.<anonymous> (XXX\node_modules\stylelint\bin\stylelint.js:8:22)
```

**Expected behavior**
The CLI usage should work without any issue as it's one of the ways this package is meant to be used.

**Versions:**
 - OS: Windows 10
 - Node: v16.13.0
 - Package: 3.0.1

**Additional context**
The Stylelint CLI is not ESM and it uses `require` to load the custom formatted, it'll throw an error.

**Comment by Dreamseer** [comment]
Thank you. As https://github.com/stylelint/stylelint/issues/5291 takes more time than expected, I’ll take a look into this and possibly create a hybrid package.

But for now, I recommend using the `2.x` versions.
